
![](https://cdn.mathpix.com/cropped/2023_03_07_431e997ed5000d9a94eeg-06.jpg?height=1550&width=1822&top_left_y=172&top_left_x=149)

![](https://cdn.mathpix.com/cropped/2023_03_07_431e997ed5000d9a94eeg-06.jpg?height=43&width=1830&top_left_y=1732&top_left_x=146)

![](https://cdn.mathpix.com/cropped/2023_03_07_431e997ed5000d9a94eeg-06.jpg?height=27&width=1830&top_left_y=1773&top_left_x=145)

![](https://cdn.mathpix.com/cropped/2023_03_07_431e997ed5000d9a94eeg-06.jpg?height=41&width=1829&top_left_y=1798&top_left_x=148)

![](https://cdn.mathpix.com/cropped/2023_03_07_431e997ed5000d9a94eeg-06.jpg?height=33&width=1827&top_left_y=1832&top_left_x=146)

![](https://cdn.mathpix.com/cropped/2023_03_07_431e997ed5000d9a94eeg-06.jpg?height=38&width=1827&top_left_y=1865&top_left_x=146)

![](https://cdn.mathpix.com/cropped/2023_03_07_431e997ed5000d9a94eeg-06.jpg?height=33&width=1825&top_left_y=1897&top_left_x=150)

![](https://cdn.mathpix.com/cropped/2023_03_07_431e997ed5000d9a94eeg-06.jpg?height=36&width=1825&top_left_y=1928&top_left_x=150)
clumps.

produce density jumps of orders of magnitude at the spiral arm interfaces.

The highest densities are reached in self-gravitating gaseous clumps. These clumps develop within the spiral arms due to local gravitational instabilities (e.g., Agertz et al. 2009b; Dekel et al. 2009; Bournaud et al. 2010). Several examples of such clumps are circled in Figure 1(a). In contrast to spiral arms, these high-density clumps are persistent physical objects rather than waves, and so they may survive for a significant period of time. Examination of disk evolution shows that some of the clumps last up to a couple of disk revolutions, until they are disrupted by feedback or merged with the gas concentration in the disk center, as also found in a number of other recent studies (e.g., Genel et al. 2012). The long-lasting clumps may themselves drive the formation of the disk spiral structure (e.g., D'Onghia et al. 2013).

Hot rarefied bubbles of gas are another kind of prominent feature seen in Figures 1(a) and (b). Some of these bubbles are inflated by exploding SNe in the regions with active star formation. Local injections of SN energy and momentum affect the distribution of dense cold gas, as they disrupt gaseous clumps and tear spiral arms apart. Sometimes, as in the case of the large hot spot near the marker "B," the hot gas instead is being pushed into the disk plane from the hot halo $\left(T \approx T_{\mathrm{vir}} \sim\right.$ $\left.10^{6} \mathrm{~K}\right)$ in regions where the disk is thinned and its gas pressure is low. 