Bolatto, A. D., Leroy, A. K., Rosolowsky, E., Walter, F., \& Blitz, L. 2008, ApJ, 686, 948

Bournaud, F., Elmegreen, B. G., Teyssier, R., Block, D. L., \& Puerari, I. 2010, MNRAS, 409, 1088

Braun, H., \& Schmidt, W. 2012, MNRAS, 421, 1838

Braun, H., \& Schmidt, W. 2015, MNRAS, 454, 1545

Braun, H., Schmidt, W., Niemeyer, J. C., \& Almgren, A. S. 2014, MNRAS, 442,3407

Bryan, G. L., Norman, M. L., Stone, J. M., Cen, R., \& Ostriker, J. P. 1995, CoPhC $, 89,149$

Cen, R., \& Ostriker, J. P. 1992, ApJL, 399, L113

Ceverino, D., \& Klypin, A. 2009, ApJ, 695, 292

Chandrasekhar, S. 1951, RSPSA, 210, 26

Clark, P. C., Bonnell, I. A., Zinnecker, H., \& Bate, M. R. 2005, MNRAS, 359,809

Colella, P., \& Glaz, H. M. 1985, JCoPh, 59, 264

D'Onghia, E., Vogelsberger, M., \& Hernquist, L. 2013, ApJ, 766, 34

Dekel, A., Sari, R., \& Ceverino, D. 2009, ApJ, 703, 785

Dobbs, C. L., Burkert, A., \& Pringle, J. E. 2011, MNRAS, 413, 2935

Evans, N. J., II, Heiderman, A., \& Vutisalchavakul, N. 2014, ApJ, 782, 114

Federrath, C. 2015, MNRAS, 450, 4035

Federrath, C., \& Klessen, R. S. 2012, ApJ, 761, 156

Federrath, C., Schron, M., Banerjee, R., \& Klessen, R. S. 2014, ApJ, 790, 128

Gammie, C. F., \& Ostriker, E. C. 1996, ApJ, 466, 814

Gammie, C. F., Ostriker, J. P., \& Jog, C. J. 1991, ApJ, 378, 565

Garnier, E., Adams, N., \& Sagaut, P. 2009, Large Eddy Simulation for Compressible Flows (The Netherlands: Springer)

Genel, S., Naab, T., Genzel, R., et al. 2012, ApJ, 745, 11

Gnedin, N. Y., Tassis, K., \& Kravtsov, A. V. 2009, ApJ, 697, 55

Governato, F., Brook, C., Mayer, L., et al. 2010, Natur, 463, 203

Heiderman, A., Evans, N. J., II, Allen, L. E., Huard, T., \& Heyer, M. 2010, ApJ, 723, 1019

Hennebelle, P., \& Chabrier, G. 2013, ApJ, 770, 150

Hernquist, L. 1990, ApJ, 356, 359

Hopkins, P. F., Keres, D., Onorbe, J., et al. 2014, MNRAS, 445, 581

Hopkins, P. F., Narayanan, D., \& Murray, N. 2013, MNRAS, 432, 2647

Hopkins, P. F., Quataert, E., \& Murray, N. 2011, MNRAS, 417, 950

Iapichino, L., Schmidt, W., Niemeyer, J. C., \& Merklein, J. 2011, MNRAS, 414,2297

Kalberla, P. M. W., \& Dedes, L. 2008, A\&A, 487, 951

Katz, N. 1992, ApJ, 391, 502

Kennicutt, R. C., \& Evans, N. J. 2012, ARA\&A, 50, 531

Kennicutt, R. C., Jr. 1998, ApJ, 498, 541

Khokhlov, A. 1998, JCoPh, 143, 519

Kim, C.-G., \& Basu, S. 2013, ApJ, 778, 88

Kim, J.-h., Abel, T., Agertz, O., et al. 2014, ApJS, 210, 14

Kravtsov, A. V. 1999, PhD thesis, New Mexico State Univ.

Kravtsov, A. V., Klypin, A., \& Hoffman, Y. 2002, ApJ, 571, 563

Kravtsov, A. V., Klypin, A. A., \& Khokhlov, A. M. 1997, ApJS, 111, 73 Kritsuk, A. G., Lee, C. T., \& Norman, M. L. 2013, MNRAS, 436, 3247

Kritsuk, A. G., Nordlund, A., Collins, D., et al. 2011, ApJ, 737, 13

Krumholz, M. R., Dekel, A., \& McKee, C. F. 2012a, ApJ, 745, 69

Krumholz, M. R., Klein, R. I., \& McKee, C. F. 2012b, ApJ, 754, 71

Krumholz, M. R., \& McKee, C. F. 2005, ApJ, 630, 250

Lada, C. J., Lombardi, M., \& Alves, J. F. 2010, ApJ, 724, 687

Larson, R. B. 1981, MNRAS, 194, 809

Latif, M. A., Schleicher, D. R. G., Schmidt, W., \& Niemeyer, J. C. 2013, MNRAS, 436, 2989

Leveque, E., Toschi, F., Shao, L., \& Bertoglio, J.-P. 2007, JFM, 570, 491

Lewis, A. R., Dolphin, A. E., Dalcanton, J. J., et al. 2015, ApJ, 805, 183

Mac Low, M.-M., Klessen, R. S., Burkert, A., \& Smith, M. D. 1998, PhRvL, 80,2754

Machacek, M. E., Bryan, G. L., \& Abel, T. 2001, ApJ, 548, 509

Maier, A., Iapichino, L., Schmidt, W., \& Niemeyer, J. C. 2009, ApJ, 707, 40

Martizzi, D., Faucher-Giguere, C.-A., \& Quataert, E. 2015, MNRAS, 450, 504

Meidt, S. E., Schinnerer, E., Garcia-Burillo, S., et al. 2013, ApJ, 779, 45

Miller, G. E., \& Scalo, J. M. 1979, ApJS, 41, 513

Misiriotis, A., Xilouris, E. M., Papamastorakis, J., Boumis, P., \& Goudis, C. D 2006, A\&A, 459, 113

Murray, N. 2011, ApJ, 729, 133

Nakanishi, H., \& Sofue, Y. 2015, PASJ, 68, 5

Navarro, J. F., Frenk, C. S., \& White, S. D. M. 1997, ApJ, 490, 493

Padoan, P., Haugblle, T., \& Nordlund, A. 2012, ApJL, 759, L27

Padoan, P., \& Nordlund, A. 2011, ApJ, 730, 40

Petric, A. O., \& Rupen, M. P. 2007, AJ, 134, 1952

Price, D. J., \& Bate, M. R. 2009, MNRAS, 398, 33

Rebolledo, D., Wong, T., Xue, R., et al. 2015, ApJ, 808, 99

Robertson, B., \& Goldreich, P. 2012, ApJL, 750, L31

Robertson, B. E., \& Kravtsov, A. V. 2008, ApJ, 680, 1083

Ropke, F. K., Hillebrandt, W., Schmidt, W., et al. 2007, ApJ, 668, 1132

Rudd, D. H., Zentner, A. R., \& Kravtsov, A. V. 2008, ApJ, 672, 19

Sagaut, P. 2006, Large Eddy Simulation for Incompressible Flows (Berlin: Springer)

Schmidt, M. 1959, ApJ, 129, 243

Schmidt, M. 1963, ApJ, 137, 758

Schmidt, W. 2014, Numerical Modelling of Astrophysical Turbulence (Berlin: Springer)

Schmidt, W., Almgren, A. S., Braun, H., et al. 2014, MNRAS, 440, 3051

Schmidt, W., \& Federrath, C. 2011, A\&A, 528, A106

Stinson, G., Seth, A., Katz, N., et al. 2006, MNRAS, 373, 1074

Stinson, G. S., Brook, C., Maccio, A. V., et al. 2013, MNRAS, 428, 129

Stone, J. M., Ostriker, E. C., \& Gammie, C. F. 1998, ApJL, 508, L99

Tamburro, D., Rix, H.-W., Leroy, A. K., et al. 2009, AJ, 137, 4424

Truelove, J. K., Klein, R. I., McKee, C. F., et al. 1997, ApJL, 489, L179

van Leer, B. 1979, JCoPh, 32, 101

Wang, P., Li, Z.-Y., Abel, T., \& Nakamura, F. 2010, ApJ, 709, 27

Zel'dovich, Y. B., \& Raizer, Y. P. 1967, Physics of Shock Waves and HighTemperature Hydrodynamic Phenomena (New York: Academic)