The SFR then is estimated assuming a static gas density probability distribution function (PDF), predicted by turbulent cloud simulations. The dependence of star formation on properties of turbulence, such as the average Mach number, arises in these models via dependence of the gas density PDF on such properties. As a result, these models generically predict variation of SFE with the Mach number, magnetic field strength, and the so-called virial parameter $\alpha_{\text {vir }}$, which parameterizes the relative importance of turbulence with respect to gravity in a given region.

Recent high-resolution simulations of self-gravitating turbulent clouds have reached the stage of resolving gravitationally unstable dense clumps, thus allowing modeling of star formation in GMCs (Clark et al. 2005; Price \& Bate 2009; Wang et al. 2010; Krumholz et al. 2012b; Padoan et al. 2012; Federrath 2015). The density PDF and other relevant physical properties and processes are evolved more or less selfconsistently, and SFE is usually estimated directly by counting the total mass of sink particles formed over a certain period of time. Remarkably, Padoan et al. (2012) found that in such simulations the relatively complex dependencies of star formation on turbulence properties suggested by the analytic models are replaced by a simple exponential relation between $\epsilon_{\mathrm{ff}}$ and cloud virial parameter, $\alpha_{\mathrm{vir}}$, only.

These results pave a way to modeling $\epsilon_{\mathrm{ff}}$ in galaxy formation simulations. However, implementation of such a model requires information on gas motions on sub-GMC scales to compute $\alpha_{\mathrm{vir}}$, which is not readily available. This is because star formation is implemented on the resolution scale of such simulations, on which gas motions are strongly affected by numerical viscosity. For example, in grid-based hydrodynamics codes this effect becomes significant on scales as large as $\approx 10-20$ computational cells (Kritsuk et al. 2011) and should be even larger in simulations using smooth particle hydrodynamics due to explicit artificial viscosity. Thus, even though state-of-the-art galaxy formation simulations reach resolutions from a few to hundreds of parsecs, gas motions can only be trusted on scales at least an order of magnitude larger.

One of the promising alternative ways to assess small-scale turbulence in hydrodynamical simulations is subgrid-scale (SGS) modeling. Models of this kind have been developed and extensively used in simulations of terrestrial turbulent subsonic and supersonic flows (see, e.g., Sagaut 2006; Garnier et al. 2009, for review). The main idea of these models lies in averaging hydrodynamics equations of turbulent flow on a certain scale $\Delta$, which is often associated with a computational cell size. The resulting set of equations then governs flows on scales $>\Delta$ and contains terms that depend on integral properties of turbulence at scales $<\Delta$. Turbulent energy at scales $<\Delta$ is also modeled as a separate field similar to gas thermal energy.

SGS turbulence modeling was implemented in a number of astrophysical studies (e.g., RApke et al. 2007; Maier et al. 2009; Iapichino et al. 2011). Schmidt et al. (2014) describe such an SGS model in the context of cosmological structure formation. Notably, galaxy formation simulations have already started using this model for nonresolved turbulence treatment as well (Latif et al. 2013; Braun et al. 2014; Braun \& Schmidt 2015).

In this study, we use the SGS turbulence model of Schmidt et al. (2014) to investigate the variation of SFE in an isolated disk simulation of a Milky-Way-sized galaxy. The main goal of this paper is to assess the viability of using the GMC-scale modeling results of Padoan et al. (2012) in galaxy-scale simulations.

Our results show that such a model predicts a wide variation of $\epsilon_{\mathrm{ff}}$ and is broadly consistent with observations both on the GMC scale and on the scale of the entire galaxy. Furthermore, we demonstrate that this model naturally results in an effective physical density threshold for star formation. This allows us to avoid arbitrary assumptions about such a critical density and temperature for star formation, often adopted in modern galaxy formation simulations. The model also does not require explicit modeling of molecular hydrogen. The SF prescription based on the Padoan et al. (2012) results thus looks promising for galaxy formation simulations.

The rest of the paper is organized as follows. In Section 2 we outline our methods and initial conditions and discuss the SGS turbulence model and the adopted prescriptions for star formation and feedback. In Section 3 we present our main results on the global disk structure, properties of the SGS turbulence, and the resulting SFRs. We also show that the predicted wide distribution of SFE is consistent with local observations of GMCs, as well as with large-scale SFRs of the Milky Way and nearby galaxies. In Section 4 we discuss our main results and compare them to previous numerical findings. Section 5 summarizes our results and conclusions.

\section{NUMERICAL MODEL}

In order to investigate the effect of small-scale turbulence on star formation, we simulate an isolated Milky-Way-sized disk galaxy with a model for SGS turbulence, a star formation prescription motivated by GMC-scale simulations, and a stellar feedback model based on subgrid evolution of supernova (SN) remnants.

We perform our simulation with the Adaptive Refinement Tree (ART) $N$-body and gas dynamics code (Kravtsov 1999; Kravtsov et al. 2002; Rudd et al. 2008). The ART code is a Eulerian code that employs an Adaptive Mesh Refinement (AMR) technique with the Fully Threaded Tree data structure (Khokhlov 1998) and a shock-capturing second-order Godunov-type method (Colella \& Glaz 1985) with piecewise linear reconstruction (van Leer 1979) to compute hydrodynamical fluxes. The Poisson equation for gas self-gravity and collisionless dynamics of stellar and dark matter particles is solved using the fast Fourier transform on the zeroth uniform grid level and the relaxation method on the refinement levels (Kravtsov et al. 1997). Gravitational potential and accelerations are used to update positions and velocities of collisionless particles and are also applied in the gas momentum and energy equations as source terms.

The SGS turbulence model is implemented by introducing additional terms, which mediate interactions of resolved and unresolved flows, into momentum and energy equations (see Section 2.1 for details). Our code separately follows the evolution of thermal and subgrid turbulent energies. Thermal energy is used to follow dissipative thermodynamics of the gas, while the subgrid turbulent energy is used to compute SFE, as well as the SGS terms in the fluid dynamics equations. In order to prevent strong fragmentation of cold gas on the resolution scale, we add artificial pressure support (e.g., Machacek et al. 2001). 