3. The density power spectrum is instead substantially shallower than in weakly compressible turbulent flows.

4. The kinetic energy power spectrum (built on $\boldsymbol{w} \equiv \sqrt{\rho} \boldsymbol{u}$ ) is shallower than Kolmogorov's 5/3 law. The power spectra for both the solenoidal and the dilatational parts of $\boldsymbol{w}$ obtained through Helmholtz decomposition $\left(\boldsymbol{w}=\boldsymbol{w}_{S}+\boldsymbol{w}_{D}\right)$ have the same slopes as the total kinetic energy spectrum pointing to the unique energy cascade captured by $E(k)$; their shares in the total energy balance are $68 \%$ and $32 \%$, respectively.

5. As should have been expected, the mean volume energy transfer rate in compressible turbulent flows, $\rho u^{2} u / l$, is very close to constant in a statistical steady state. Our simulations show that the power spectrum of $\boldsymbol{v} \equiv \rho^{1 / 3} \boldsymbol{u}$ scales approximately as $k^{-5 / 3}$ and the third-order structure function of $v$ scales linearly with $l$ in the inertial range.

6. The directly measured mass dimension of the "fractal" density distribution is about 2.4 in the inertial range and 2.0 in the dissipation range. The geometry of supersonic turbulence is dominated by clustered corrugated shock fronts.

These results strongly suggest that the Kolmogorov laws originally derived for incompressible turbulence would also hold for highly compressible flows as soon as they are extended by replacing the pure velocity statistics with statistics of mixed quantities, such as the density-weighted fluid velocity $\boldsymbol{v} \equiv \rho^{1 / 3} \boldsymbol{u}$.

Both the scaling properties and the geometry of supersonic turbulence we find in our numerical experiments support a phenomenological description of intermittent energy cascade in a compressible turbulent fluid and suggest a reformulation of inertial range intermittency models for compressible turbulence in terms of the proposed extension to the K41 theory.

The scaling exponents of the velocity diagnostics, the morphology of turbulent structures, and the fractal dimension of the mass distribution determined in our numerical experiments demonstrate good agreement with the corresponding observed quantities in supersonically turbulent molecular clouds and line radiationdriven winds from carbon-sequence Wolf-Rayet stars.

We are grateful to Ake Nordlund who kindly provided us with his OpenMP parallel routines to compute the power spectra. This research was partially supported by NASA ATP grant NNG 05 6601G, NSF grants AST 05-07768 and AST 06-07675, and NRAC allocation MCA 098020S. We utilized computing resources provided by the San Diego Supercomputer Center and the National Center for Supercomputer Applications.

\section{REFERENCES}

Acker, A., Gesicki, K., Grosdidier, Y., \& Durand, S. 2002, A\&A, 384, 620

Armi, L., \& Flament, P. 1985, J. Geophys. Res., 90, 11779

Armstrong, J. W., Rickett, B. J., \& Spangler, S. R. 1995, ApJ, 443, 209

Baty, H., Keppens, R., \& Comte, P. 2003, Phys. Plasmas, 10, 4661

Bayly, B. J., Levermore, C. D., \& Passot, T. 1992, Phys. Fluids, 4, 945

Benzi, R., Biferale, L., Ciliberto, S., Struglia, M. V., \& Tripiccione, R. 1996, Physica D, 96, 162

Benzi, R., Ciliberto, S., Tripiccione, R., Baudet, C., Massaioli, F., \& Succi, S. 1993, Phys. Rev. E, 48, R29

Biglari, H., \& Diamond, P. H. 1988, Phys. Rev. Lett., 61, 1716

.1989, Physica D, 37, 206

Boldyrev, S. 2002, ApJ, 569, 841

Boldyrev, S., Nordlund, A., \& Padoan, P. 2002, ApJ, 573, 678

Brunt, C. M. 2003, ApJ, 584, 293

Brunt, C. M., Heyer, M. H., Vazquez-Semadeni, E., \& Pichardo, B. 2003, ApJ, 595,824

Colella, P., \& Woodward, P. R. 1984, J. Comput. Phys., 54, 174

Davidson, P. A., \& Pearson, B. R. 2005, Phys. Rev. Lett., 95, 214501

de Karman, T., \& Howarth, L. 1938, Proc. R. Soc. London A, 164, 192

Dickman, R. L. 1978, ApJS, 37, 407

Dobler, W., Haugen, N. E., Yousef, T. A., \& Brandenburg, A. 2003, Phys. Rev. E, 68,026304

Dubrulle, B. 1994, Phys. Rev. Lett., 73, 959

Elmegreen, B. G., \& Elmegreen, D. M. 2001, AJ, 121, 1507

Elmegreen, B. G., \& Falgarone, E. 1996, ApJ, 471, 816

Elmegreen, B. G., \& Scalo, J. 2004, ARA\&A, 42, 211

Falkovich, G. 1994, Phys. Fluids, 6, 1411

Fleck, R. C., Jr. 1996, ApJ, 458, 739

Frisch, U. 1995, Turbulence: The Legacy of A. N. Kolmogorov (Cambridge: Cambridge Univ. Press)

Frisch, U., \& Bec, J. 2001, in Les Houches 2000: New Trends in Turbulence, ed. M. Lesieur, A. Yaglom, \& F. David (Berlin: Springer), 341

Gaffet, B. 1985, J. Fluid Mech., 156, 141

Grosdidier, Y., Moffat, A. F. J., Blais-Ouellette, S., Joncas, G., \& Acker, A. 2001, ApJ, 562, 753

Haugen, N. E., \& Brandenburg, A. 2004, Phys. Rev. E, 70, 026405

Heitsch, F., Burkert, A., Hartmann, L. W., Slyz, A. D., \& Devriendt, J. E. G. 2005, ApJ, 633, L113

Helmholtz, H. 1868, Monasber. Berlin Akad., 215

Kaneda, Y., Ishihara, T., Yokokawa, M., Itakura, K., \& Uno, A. 2003, Phys. Fluids, 15, L21

Kaplan, S. A., \& Pikelner, S. B. 1970, The Interstellar Medium (Cambridge: Harvard Univ. Press)

Kaplan, S. A., \& Pronik, V. I. 1953, Akad. Nauk SSSR Dokl., 89, 643

Keppens, R., Toth, G., Westermann, R. H. J., \& Goedbloed, J. P. 1999, J. Plasma Phys., 61, 1 Kida, S., \& Orszag, S. A. 1990, J. Sci. Comput., 5, 85

_. 1992, J. Sci. Comput., 7, 1

Kim, J., \& Ryu, D. 2005, ApJ, 630, L45

Kolmogorov, A. N. 1941a, Akad. Nauk SSSR Dokl., 30, 299 (K41)

_. 1941b, Akad. Nauk SSSR Dokl., 31, 538

-. 1941c, Akad. Nauk SSSR Dokl., 32, 19

1962, J. Fluid Mech., 13, 82

Kornreich, P., \& Scalo, J. 2000, ApJ, 531, 366

Kritsuk, A. G., \& Norman, M. L. 2004, ApJ, 601, L55

Kritsuk, A. G., Norman, M. L., \& Padoan, P. 2006, ApJ, 638, L25

Larson, R. B. 1981, MNRAS, 194, 809

Lazarian, A., \& Pogosyan, D. 2000, ApJ, 537, 720 2006, ApJ, 652, 1348

Lele, S. K. 1994, Ann. Rev. Fluid Mech., 26, 211

Li, P. S., Norman, M. L., Mac Low, M.-M., \& Heitsch, F. 2004, ApJ, 605, 800

Lighthill, M. J. 1955, in IAU Symp. 2, Gas Dynamics of Cosmic Clouds (Amsterdam: North Holland), 121

Liu, J., She, Z.-S., Guo, H., Li, L., \& Ouyang, Q. 2004, Phys. Rev. E, 70, 036215

Mac Low, M.-M., \& Klessen, R. S. 2004, Rev. Mod. Phys., 76, 125

Mandelbrot, B. B. 1974, J. Fluid Mech., 62, 331

_. 1975, J. Fluid Mech., 72, 401

Meneveau, C., \& Sreenivasan, K. R. 1990, Phys. Rev. A, 41, 2246

Miles, J. W. 1957, J. Fluid Mech., 3, 185

Mininni, P. D., Alexakis, A., \& Pouquet, A. 2006, Phys. Rev. E, 74, 016303

Miura, A., \& Pritchett, P. L. 1982, J. Geophys. Res., 87, 7431

Monin, A. S., \& Yaglom, A. M. 1975, Statistical Fluid Mechanics: Mechanics of Turbulence, Vol. 2 (Cambridge: MIT Press)

Moyal, J. E. 1951, Proc. Cambridge Philos. Soc., 48, 329

Nordlund, A. K., \& Padoan, P. 1999, in Interstellar Turbulence, ed. J. Franco \& A. Carraminana (Cambridge: Cambridge Univ. Press), 218

Norman, C. A., \& Ferrara, A. 1996, ApJ, 467, 280

Obukhov, A. M. 1941, Akad. Nauk SSSR Dokl., 32, 22

- 1962, J. Fluid Mech., 13, 77

Padoan, P., Jimenez, R., Juvela, M., \& Nordlund, A. 2004a, ApJ, 604, L49

Padoan, P., Jimenez, R., Nordlund, A., \& Boldyrev, S. 2004b, Phys. Rev. Lett., 92,191102

Padoan, P., Juvela, M., Kritsuk, A., \& Norman, M. L. 2006, ApJ, 653, L125

Padoan, P., \& Nordlund, A. 1997, preprint (astro-ph/9706176)

- 1999, ApJ, 526, 279

- 2002, ApJ, 576, 870

Padoan, P., Nordlund, A., \& Jones, B. J. T. 1997, MNRAS, 288, 145

Padoan, P., Nordlund, A., Kritsuk, A. G., Norman, M. L., \& Li, P. S. 2007, ApJ, 661,972

Passot, T., Pouquet, A., \& Woodward, P. 1988, A\&A, 197, 228

Passot, T., \& Vazquez-Semadeni, E. 1998, Phys. Rev. E, 58, 4501

Politano, H., \& Pouquet, A. 1998, Geophys. Res. Lett., 25, 273 