

![](https://cdn.mathpix.com/cropped/2023_03_07_bafffa1b75e24c88ed67g-07.jpg?height=593&width=882&top_left_y=217&top_left_x=130)

Fig. 10.-First-order velocity structure functions and the best-fit power laws for $\log _{10}(l / \Delta) \in[1.5,2.5]$. [See the electronic edition of the Journal for a color version of this figure.]

![](https://cdn.mathpix.com/cropped/2023_03_07_bafffa1b75e24c88ed67g-07.jpg?height=604&width=879&top_left_y=1102&top_left_x=132)

FIG. 11.-Same as Fig. 10, but for the second-order structure functions. [See the electronic edition of the Journal for a color version of this figure.]

![](https://cdn.mathpix.com/cropped/2023_03_07_bafffa1b75e24c88ed67g-07.jpg?height=602&width=879&top_left_y=1968&top_left_x=132)

FIG. 12.-Same as Fig. 10, but for the third-order structure functions. [See the electronic edition of the Journal for a color version of this figure.] total specific kinetic energy, and being responsible for up to $35 \%$ of the global dissipation rate (see $\S 3.1$ ).

\subsection{Velocity Structure Functions}

To substantiate this result, we studied the scaling properties of the velocity structure functions (e.g., Monin \& Yaglom 1975)

$$S_{p}(l) \equiv\left\langle|\boldsymbol{u}(\boldsymbol{r}+\boldsymbol{l})-\boldsymbol{u}(\boldsymbol{r})|^{p}\right\rangle$$

of orders $p=1,2$, and 3 , where the averaging $\langle\ldots\rangle$ is taken over all positions $\boldsymbol{r}$ and all orientations of $\boldsymbol{l}$ within the computational domain. Both longitudinal $(\boldsymbol{u} \| \boldsymbol{l})$ and transverse $(\boldsymbol{u} \perp \boldsymbol{l})$ structure functions can be well approximated by power laws in the inertial range

$$S_{p}(l) \propto l^{\zeta_{p}},$$

see Figures 10-12. The low-order structure functions are less susceptible to the bottleneck contamination and might be better suited for deriving the scaling exponents (Dobler et al. 2003). ${ }^{6}$ Let us now check how close the exponents derived from the data are to the $\mathrm{K} 41$ prediction $\zeta_{p}=p / 3$.

It is natural to begin with the second-order structure functions, since the velocity power spectrum $\mathcal{E}(k)$ is the Fourier transform of $S_{2}(l)$ and therefore $\beta=\zeta_{2}+1$. The best-fit second-order exponents measured for the range of scales $l$ between $32 \Delta$ and $256 \Delta, \zeta_{2}^{\|}=0.952 \pm 0.004$ and $\zeta_{2}^{\perp}=0.977 \pm 0.008$, are substantially larger than the K41 value of $2 / 3$ and, within the statistical uncertainty, agree with our measured velocity power index $\beta=1.95 \pm 0.02$. In homogeneous isotropic incompressible turbulence, $S_{2}^{\perp}$ is uniquely determined by $S_{2}^{\|}$(and vice versa) via the first de Karman \& Howarth (1938) relation,

$$S_{2}^{\perp}=S_{2}^{\|}+\frac{l}{2} S_{2}^{\| \prime}$$

For the K41 inertial range velocity scaling, this translates into

$$S_{2}^{\perp}=\frac{4}{3} S_{2}^{\|} .$$

At Mach 6, the second-order longitudinal and transverse structure functions are also approximately parallel to each other in the $(\log S, \log l)$-plane, but the offset between them, $S_{2}^{\perp} / S_{2}^{\|} \approx 1.27$, is somewhat smaller than the $\mathrm{K} 41$ value of $4 / 3$. This suggests that in highly compressible regimes some generalization of the first Karman-Howarth relation still remains valid, even though a substantial fraction of the specific kinetic energy (up to $1 / 3$ at $\mathcal{M}=6$ ) is concentrated in the dilatational component (cf. Moyal 1951; Samtaney et al. 2001).

The first-order exponents $\zeta_{1}^{\|}=0.533 \pm 0.002$ and $\zeta_{1}^{\perp}=$ $0.550 \pm 0.004$ are again significantly larger than the $\mathrm{K} 41$ index of $1 / 3$ but also considerably smaller than the index of 1 for the Burgers model (e.g., Frisch \& Bec 2001). Observationally determined exponents for the molecular cloud turbulence are normally found within the range from 0.4 to 0.8 (Brunt et al. 2003), in reasonable agreement with our result.

We find that the third-order scaling exponents $\zeta_{3}^{\|}=1.26 \pm$ 0.01 and $\zeta_{3}^{\perp}=1.29 \pm 0.01$ are also noticeably off from $\zeta_{3}=1$

6 Note, however, that the bottleneck corrections grow with the order $p$ (Falkovich 1994) and influence the structure functions in a nonlocal fashion, mixing small- and large-scale information (Dobler et al. 2003; Davidson \& Pearson 2005). 