Porter, D. H., Pouquet, A., Sytine, I., \& Woodward, P. 1999, Physica A, 263, 263 Porter, D. H., Pouquet, A., \& Woodward, P. R. 1992a, Theor. Comput. Fluid Dynamics, 4, 13

1992b, Phys. Rev. Lett., 68, 3156

1994, Phys. Fluids, 6, 2133

2002, Phys. Rev. E, 66, 026301

Porter, D. H., \& Woodward, P. R. 1994, ApJS, 93, 309

Porter, D. H., Woodward, P. R., \& Pouquet, A. 1998, Phys. Fluids, 10, 237

Pouquet, A., Passot, T., \& Leorat, J. 1991, in IAU Symp. 147, Fragmentation of Molecular Clouds and Star Formation, ed. E. Falgarone, F. Boulanger, \& G Duvert (Dordrecht: Kluwer), 101 Ryu, D., Jones, T. W., \& Frank, A. 2000, ApJ, 545, 475

Samtaney, R., Pullin, D. I., \& Kosovic, B. 2001, Phys. Fluids, 13, 1415

She, Z.-S., \& Leveque, E. 1994, Phys. Rev. Lett., 72, 336

She, Z.-S., \& Waymire, E. C. 1995, Phys. Rev. Lett., 74, 262

Sreenivasan, K. R., \& Bershadskii, A. 2005, Pramana J. Phys., 64, 315

Sytine, I. V., Porter, D. H., Woodward, P. R., Hodson, S. W., \& Winkler, K.-H. 2000, J. Comput. Phys., 158, 225

Vazquez-Semadeni, E. 1994, ApJ, 423, 681

Vishniac, E. T. 1994, ApJ, 428, 186

von Weizsacker, C. F. 1951, ApJ, 114, 165